version: '3.1'

services:
  nginx:
    build:
      context: ./Nginx_server_config/
      dockerfile: Dockerfile
    ports:
      - 1789:80
      - 1790:81
      - 1791:82
    networks:
      - my-network
    depends_on:
      - flask_admin
      - flask_client
      - my_mongo
    restart: always

  flask_admin:
    build:
      context: ./admin/
      dockerfile: Dockerfile
    container_name: flask_admin
    command: gunicorn --bind 0.0.0.0:8001 --workers=2 --timeout=120 "apiControl:app"
    networks:
      my-network:
        aliases:
          - flask-app1
    depends_on:
      - my_mongo
    volumes:
      - "./MangaScan:/appli/LOCALdata"
    restart: always
      
  flask_client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: flask_client
    command: gunicorn --bind 0.0.0.0:9001 --workers 4 "main:app"
    networks:
      my-network:
        aliases:
          - flask-app2
    depends_on:
      - my_mongo
    restart: always
  
  my_mongo:
    build:
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - "./database/mongoDump:/data/backup"
      - "./database/current_database:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
  
  apache_scans:
    build:
      context: ./apache_scans/
      dockerfile: Dockerfile
    volumes:
        - "./MangaScan:/usr/local/apache2/htdocs/scans"
    ports:
        - 1987:80
    restart: always

networks:
  my-network:
    driver: bridge